up

diff --git a/.github/workflows/mdbook.yml b/.github/workflows/mdbook.yml
--- a/.github/workflows/mdbook.yml
+++ b/.github/workflows/mdbook.yml
@@ -18,18 +18,21 @@ jobs:
 
     - name: Install mdBook
       run: cargo install mdbook
+
+    - name: Install mdbook-catppuccin
+      run: cargo install mdbook-catppuccin
     
-    - name: Build mdBook
+    - name: Build the docs to HTML/JS/CSS
       run: mdbook build
     
-    - name: 'Cleanup build folder'
-      run: |
-        git checkout -b gh-pages
-        ls -la ./
-        rm -rf ./* || true
-        rm -rf ./.??* || true
-        ls -la ./
-        git checkout -b master
+    # - name: 'Cleanup build folder'
+    #   run: |
+    #     git checkout -b gh-pages
+    #     ls -la ./
+    #     rm -rf ./* || true
+    #     rm -rf ./.??* || true
+    #     ls -la ./
+    #     git checkout -b master
         
     - name: Commit and Push Changes
       run: |
